<a href="https://colab.research.google.com/github/oms0401/credit_loan_prediction/blob/main/Credit_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from scipy.stats import chi2_contingency
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, precision_recall_fscore_support
import warnings
import os

In [2]:
# Load the dataset
a1 = pd.read_excel("/content/case_study1.xlsx")
a2 = pd.read_excel("/content/case_study2.xlsx")

In [3]:
df1 = a1.copy()
df2 = a2.copy()

In [4]:
# Remove nulls
df1 = df1.loc[df1['Age_Oldest_TL'] != -99999]




columns_to_be_removed = []

for i in df2.columns:
    if df2.loc[df2[i] == -99999].shape[0] > 10000:
        columns_to_be_removed .append(i)

df2 = df2.drop(columns_to_be_removed, axis =1)



for i in df2.columns:
    df2 = df2.loc[ df2[i] != -99999 ]

In [5]:
# Checking common column names
for i in list(df1.columns):
    if i in list(df2.columns):
        print (i)




# Merge the two dataframes, inner join so that no nulls are present
df = pd. merge ( df1, df2, how ='inner', left_on = ['PROSPECTID'], right_on = ['PROSPECTID'] )

PROSPECTID

In [6]:
# check how many columns are categorical
for i in df.columns:
    if df[i].dtype == 'object':
        print(i)



# Chi-square test
for i in ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']:
    chi2, pval, _, _ = chi2_contingency(pd.crosstab(df[i], df['Approved_Flag']))
    print(i, '---', pval)


# Since all the categorical features have pval <=0.05, we will accept all

MARITALSTATUS
EDUCATION
GENDER
last_prod_enq2
first_prod_enq2
Approved_Flag
MARITALSTATUS --- 3.578180861038862e-233
EDUCATION --- 2.6942265249737532e-30
GENDER --- 1.907936100186563e-05
last_prod_enq2 --- 0.0
first_prod_enq2 --- 7.84997610555419e-287

In [8]:
# VIF sequentially check

# VIF for numerical columns
numeric_columns = []
for i in df.columns:
    if df[i].dtype != 'object' and i not in ['PROSPECTID','Approved_Flag']:
        numeric_columns.append(i)

vif_data = df[numeric_columns]
total_columns = vif_data.shape[1]
columns_to_be_kept = []
column_index = 0



for i in range (0,total_columns):

    vif_value = variance_inflation_factor(vif_data, column_index)
    print (column_index,'---',vif_value)


    if vif_value <= 6:
        columns_to_be_kept.append(numeric_columns[i] )
        column_index = column_index+1

    else:
        vif_data = vif_data.drop([numeric_columns[i] ] , axis=1)

/usr/local/lib/python3.10/dist-packages/statsmodels/stats/outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --- inf

/usr/local/lib/python3.10/dist-packages/statsmodels/stats/outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --- inf
0 --- 11.320180023967996
0 --- 8.363698035000336
0 --- 6.520647877790928
0 --- 5.149501618212625
1 --- 2.611111040579735

/usr/local/lib/python3.10/dist-packages/statsmodels/stats/outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

2 --- inf
2 --- 1788.7926256209232
2 --- 8.601028256477228
2 --- 3.832800792153077
3 --- 6.099653381646723
3 --- 5.581352009642766
4 --- 1.985584353098778

/usr/local/lib/python3.10/dist-packages/statsmodels/stats/outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

5 --- inf
5 --- 4.80953830281934
6 --- 23.270628983464636
6 --- 30.595522588100053
6 --- 4.384346405965583
7 --- 3.0646584155234238
8 --- 2.898639771299251
9 --- 4.377876915347324
10 --- 2.207853583695844
11 --- 4.916914200506864
12 --- 5.214702030064725
13 --- 3.3861625024231476
14 --- 7.840583309478997
14 --- 5.255034641721434

/usr/local/lib/python3.10/dist-packages/statsmodels/stats/outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

15 --- inf
15 --- 7.380634506427238
15 --- 1.4210050015175733
16 --- 8.083255010190316
16 --- 1.6241227524040114
17 --- 7.257811920140003
17 --- 15.59624383268298
17 --- 1.825857047132431
18 --- 1.5080839450032664
19 --- 2.172088834824578
20 --- 2.6233975535272274
21 --- 2.2959970812106176
22 --- 7.360578319196446
22 --- 2.1602387773102567
23 --- 2.8686288267891467
24 --- 6.458218003637272
24 --- 2.8474118865638247
25 --- 4.753198156284083
26 --- 16.22735475594825
26 --- 6.424377256363877
26 --- 8.887080381808678
26 --- 2.3804746142952653
27 --- 8.60951347651454
27 --- 13.06755093547673
27 --- 3.500040056654653
28 --- 1.9087955874813773
29 --- 17.006562234161628
29 --- 10.730485153719197
29 --- 2.3538497522950275
30 --- 22.10485591513649
30 --- 2.7971639638512924
31 --- 3.424171203217696
32 --- 10.175021454450922
32 --- 6.408710354561292
32 --- 1.001151196262563
33 --- 3.069197305397273
34 --- 2.8091261600643724
35 --- 20.249538381980678
35 --- 15.864576541593774
35 --- 1.833164974053215
36 --- 1.5680839909542046
37 --- 1.9307572353811682
38 --- 4.331265056645244
39 --- 9.390334396150173

In [9]:
# check Anova for columns_to_be_kept

from scipy.stats import f_oneway

columns_to_be_kept_numerical = []

for i in columns_to_be_kept:
    a = list(df[i])
    b = list(df['Approved_Flag'])

    group_P1 = [value for value, group in zip(a, b) if group == 'P1']
    group_P2 = [value for value, group in zip(a, b) if group == 'P2']
    group_P3 = [value for value, group in zip(a, b) if group == 'P3']
    group_P4 = [value for value, group in zip(a, b) if group == 'P4']


    f_statistic, p_value = f_oneway(group_P1, group_P2, group_P3, group_P4)

    if p_value <= 0.05:
        columns_to_be_kept_numerical.append(i)

In [10]:
# listing all the final features
features = columns_to_be_kept_numerical + ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']
df = df[features + ['Approved_Flag']]

In [11]:
# Label encoding for the categorical features
['MARITALSTATUS', 'EDUCATION', 'GENDER' , 'last_prod_enq2' ,'first_prod_enq2']

df['MARITALSTATUS'].unique()
df['EDUCATION'].unique()
df['GENDER'].unique()
df['last_prod_enq2'].unique()
df['first_prod_enq2'].unique()

# the priority of these are customised in nature
df.loc[df['EDUCATION'] == 'SSC',['EDUCATION']]              = 1
df.loc[df['EDUCATION'] == '12TH',['EDUCATION']]             = 2
df.loc[df['EDUCATION'] == 'GRADUATE',['EDUCATION']]         = 3
df.loc[df['EDUCATION'] == 'UNDER GRADUATE',['EDUCATION']]   = 3
df.loc[df['EDUCATION'] == 'POST-GRADUATE',['EDUCATION']]    = 4
df.loc[df['EDUCATION'] == 'OTHERS',['EDUCATION']]           = 1
df.loc[df['EDUCATION'] == 'PROFESSIONAL',['EDUCATION']]     = 3

In [16]:
df_encoded = pd.get_dummies(df, columns=['MARITALSTATUS','GENDER', 'last_prod_enq2' ,'first_prod_enq2','EDUCATION'])



df_encoded.info()
k = df_encoded.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42064 entries, 0 to 42063
Data columns (total 58 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   pct_tl_open_L6M               42064 non-null  float64
 1   pct_tl_closed_L6M             42064 non-null  float64
 2   Tot_TL_closed_L12M            42064 non-null  int64
 3   pct_tl_closed_L12M            42064 non-null  float64
 4   Tot_Missed_Pmnt               42064 non-null  int64
 5   CC_TL                         42064 non-null  int64
 6   Home_TL                       42064 non-null  int64
 7   PL_TL                         42064 non-null  int64
 8   Secured_TL                    42064 non-null  int64
 9   Unsecured_TL                  42064 non-null  int64
 10  Other_TL                      42064 non-null  int64
 11  Age_Oldest_TL                 42064 non-null  int64
 12  Age_Newest_TL                 42064 non-null  int64
 13  time_since_recent_payment     42064 non-null  int64
 14  max_recent_level_of_deliq     42064 non-null  int64
 15  num_deliq_6_12mts             42064 non-null  int64
 16  num_times_60p_dpd             42064 non-null  int64
 17  num_std_12mts                 42064 non-null  int64
 18  num_sub                       42064 non-null  int64
 19  num_sub_6mts                  42064 non-null  int64
 20  num_sub_12mts                 42064 non-null  int64
 21  num_dbt                       42064 non-null  int64
 22  num_dbt_12mts                 42064 non-null  int64
 23  num_lss                       42064 non-null  int64
 24  recent_level_of_deliq         42064 non-null  int64
 25  CC_enq_L12m                   42064 non-null  int64
 26  PL_enq_L12m                   42064 non-null  int64
 27  time_since_recent_enq         42064 non-null  int64
 28  enq_L3m                       42064 non-null  int64
 29  NETMONTHLYINCOME              42064 non-null  int64
 30  Time_With_Curr_Empr           42064 non-null  int64
 31  CC_Flag                       42064 non-null  int64
 32  PL_Flag                       42064 non-null  int64
 33  pct_PL_enq_L6m_of_ever        42064 non-null  float64
 34  pct_CC_enq_L6m_of_ever        42064 non-null  float64
 35  HL_Flag                       42064 non-null  int64
 36  GL_Flag                       42064 non-null  int64
 37  Approved_Flag                 42064 non-null  object
 38  MARITALSTATUS_Married         42064 non-null  bool
 39  MARITALSTATUS_Single          42064 non-null  bool
 40  GENDER_F                      42064 non-null  bool
 41  GENDER_M                      42064 non-null  bool
 42  last_prod_enq2_AL             42064 non-null  bool
 43  last_prod_enq2_CC             42064 non-null  bool
 44  last_prod_enq2_ConsumerLoan   42064 non-null  bool
 45  last_prod_enq2_HL             42064 non-null  bool
 46  last_prod_enq2_PL             42064 non-null  bool
 47  last_prod_enq2_others         42064 non-null  bool
 48  first_prod_enq2_AL            42064 non-null  bool
 49  first_prod_enq2_CC            42064 non-null  bool
 50  first_prod_enq2_ConsumerLoan  42064 non-null  bool
 51  first_prod_enq2_HL            42064 non-null  bool
 52  first_prod_enq2_PL            42064 non-null  bool
 53  first_prod_enq2_others        42064 non-null  bool
 54  EDUCATION_1                   42064 non-null  bool
 55  EDUCATION_2                   42064 non-null  bool
 56  EDUCATION_3                   42064 non-null  bool
 57  EDUCATION_4                   42064 non-null  bool
dtypes: bool(20), float64(5), int64(32), object(1)
memory usage: 13.0+ MB

In [17]:
df_encoded.head()

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,...,first_prod_enq2_AL,first_prod_enq2_CC,first_prod_enq2_ConsumerLoan,first_prod_enq2_HL,first_prod_enq2_PL,first_prod_enq2_others,EDUCATION_1,EDUCATION_2,EDUCATION_3,EDUCATION_4
0,0.000,0.0,0,0.000,0,0,0,4,1,4,...,False,False,False,False,True,False,False,True,False,False
1,0.000,0.0,0,0.000,0,0,0,0,0,1,...,False,False,True,False,False,False,False,False,True,False
2,0.125,0.0,0,0.000,1,0,0,0,2,6,...,False,False,False,False,False,True,True,False,False,False
3,0.000,0.0,0,0.000,0,0,0,0,3,0,...,True,False,False,False,False,False,False,False,False,True
4,0.000,0.0,1,0.167,0,0,0,0,6,0,...,False,False,False,False,True,False,False,True,False,False

In [18]:
#the training waas done on sereveral models but the best came out was xgboost would be doing the final training on lightgbm and catboost as well

#xgboost

import xgboost as xgb
from sklearn.preprocessing import LabelEncoder

xgb_classifier = xgb.XGBClassifier(objective='multi:softmax',  num_class=4)



y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )


label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)


x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)




xgb_classifier.fit(x_train, y_train)
y_pred = xgb_classifier.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print ()
print(f'Accuracy: {accuracy:.2f}')
print ()

precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.78

Class p1:
Precision: 0.8215811965811965
Recall: 0.7583826429980276
F1 Score: 0.7887179487179488

Class p2:
Precision: 0.8230151650312221
Recall: 0.914370664023786
F1 Score: 0.8662910798122067

Class p3:
Precision: 0.4657210401891253
Recall: 0.29735849056603775
F1 Score: 0.36296637494242284

Class p4:
Precision: 0.7387914230019493
Recall: 0.7366375121477162
F1 Score: 0.7377128953771289

In [19]:
# Hyperparameter tuning in xgboost
from sklearn.model_selection import GridSearchCV
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)

# Define the XGBClassifier with the initial set of hyperparameters
xgb_model = xgb.XGBClassifier(objective='multi:softmax', num_class=4)

# Define the parameter grid for hyperparameter tuning

param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
}

grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, cv=3, scoring='accuracy', n_jobs=-1)
grid_search.fit(x_train, y_train)

# Print the best hyperparameters
print("Best Hyperparameters:", grid_search.best_params_)

# Evaluate the model with the best hyperparameters on the test set
best_model = grid_search.best_estimator_
accuracy = best_model.score(x_test, y_test)
print("Test Accuracy:", accuracy)

Best Hyperparameters: {'learning_rate': 0.2, 'max_depth': 3, 'n_estimators': 200}
Test Accuracy: 0.7803399500772614

In [20]:
import pickle
# Specify the file path
filename = 'trained_model.pkl'

# Open the file in write-binary mode and dump the model
with open(filename, 'wb') as file:
    pickle.dump(best_model, file)